# -*- coding: utf-8 -*-
"""Day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQvLP0pTi0qtl-9ObDD7Op7L1SUo7Qw5
"""

email = input('enter email')
password = input ('enter password')

if email == 'akhilsoni015@gmail.com' and password == '9782ak':
  print('welcome hai ji')

else:
  print('chal nikal')

email = input('enter email')
password = input ('enter password')

if email == 'akhilsoni015@gmail.com' and password == '9782ak':
  print('welcome hai ji')
elif email == 'akhilsoni015@gmail.com' and password != '9782ak':
  print('theek nhi hai password')
  password = input('enter password again')
  if password == '9782ak':
    print('theek hai password')
  else:
    print('beta tum se nhi ho paayega!')
else:
  print('chal nikal')

a = int(input('enter first number'))
b = int(input('enter second number'))
c = int(input('enter third number'))

if a<b and a<c:
  print( 'smallest is' ,a)
elif b<c:
  print( 'smallest is'  ,b)
else:
  print('smallest is ' ,c)

import math

math.factorial(6)

import keyword

print(keyword.kwlist)

import random
print(random.randint(1,100))

help('modules')

pip install "betterproto

#loop

import random

jackpot = random.randint(1, 100)

guess = int(input('guess karo'))
counter = 1

while guess != jackpot:
  if guess < jackpot:
    print('higher')
  else:
    print('lower')
  guess = int(input('guess kro'))
  counter += 1

else:
  print('right guess')
  print('attempts',counter)

#forloop

for i in range(2, 8):
    print(i)

total = 0

for i in range(1, 6):
    total += i

print(total)

num = 7

for i in range(1, 11):
    print(num * i)

fruits = ["apple", "banana", "mango"]

for fruit in fruits:
    print(fruit)

for i in range(10, 0, -2):
    print(i)

text = "education"
count = 0

for ch in text.lower():
    if ch in "aeiou":
        count += 1

print(count)

nums = [10, 50, 20, 80, 30]

largest = second = float('-inf')

for num in nums:
    if num > largest:
        second = largest
        largest = num
    elif num > second and num != largest:
        second = num

print(second)

