# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5rtzpi0TnS4ixsXK8pPmAvJHIwQ0IDg

List / Tuples /Sets
"""

courses = ['Maths','Sci','English','Hindi','Physics']

print(courses[-1])
print(courses[0])
print(courses[1])
print(courses[2])
print(courses[3])
print(courses[4])

print(courses[0:3]) #finding a word its based on indexes
print(courses[1:3])
print(courses[3:4])
print(courses[3:])

# Modifing list
#courses.append('Art')
courses.insert(0,'Tamil')
print(courses)

#Adding multiple valuse in a list

courses_2 = ['Tamil','English']
courses.insert(0,courses_2)
print(courses)

"""### Understanding `extend()` vs `insert()`

When you used `courses.insert(0, courses_2)` previously, it inserted the entire `courses_2` list `['Tamil', 'English']` as a single element at the beginning of `courses`. This resulted in a nested list where `['Tamil', 'English']` became the first item.

The `extend()` method, on the other hand, takes an iterable (like another list) and adds *each element* of that iterable individually to the end of the current list. If you want to merge two lists without nesting them, `extend()` is the appropriate method.

To demonstrate `extend()`, let's first reset the `courses` list to a simpler state to see the effect clearly.
"""

courses = ['Maths','Sci','English','Hindi','Physics']
courses_2 = ['Tamil','Art']

print(f"Original courses list: {courses}")
print(f"List to extend with: {courses_2}")

courses.extend(courses_2)
print(f"Courses list after extend(): {courses}")

"""As you can see, `extend()` added 'Tamil' and 'Art' as individual elements to the end of the `courses` list, rather than adding `['Tamil','Art']` as a single, nested element."""

courses_2 = ['Tamil', 'English'] # Re-initializing courses_2 for demonstration
courses_2.remove('Tamil')
courses_2.remove('English')
print(courses_2)
print(courses)

print(courses)
print(courses_2)

courses.pop(1)

print(courses)

#sorting list
courses.sort()
print(courses)

# if list in number

num = [1,3,5,3,6]
num.sort()
print(num)

# reverse mathord
num.sort(reverse=True)
print(num)

# min / max / sum

print(min(num))

print(max(num))


print(sum(num))

# finding values

print(courses.index('Maths'))

#to check there is like a word or num or any thing in list
print('Maths' in courses)

# looping values

for index, course in enumerate(courses, start=1):
  print(index, course)

# list to string

#using jion matho of string

course_str = ' - '.join(courses)
print(course_str)

#tuples

# mutable
list_1 = ['Art', 'English', 'Hindi', 'Maths', 'Physics', 'Tamil']
list_2 = ['Art', 'English', 'Hindi', 'Maths', 'Physics', 'Tamil']

# immutable
tuple_1 = ('Art', 'English', 'Hindi', 'Maths', 'Physics', 'Tamil')

print(tuple_1.count('English'))

"""## Understanding Tuples

Tuples are an ordered, immutable collection of items. This means that once a tuple is created, you cannot change its contents (add, remove, or modify elements). They are defined using parentheses `()` and elements are separated by commas. While lists are suitable for collections of items that might change, tuples are used for fixed collections.

**Key characteristics of tuples:**
*   **Ordered**: The order of items in a tuple is preserved.
*   **Immutable**: Once created, elements cannot be changed, added, or removed.
*   **Indexed**: Elements can be accessed by their integer index.
*   **Allow duplicates**: Tuples can contain duplicate values.
*   **Heterogeneous**: Tuples can store items of different data types.
"""

# Creating a tuple
my_tuple = (1, 'hello', 3.14, True)
print(f"My tuple: {my_tuple}")
print(f"Type of my_tuple: {type(my_tuple)}")

# Accessing elements (just like lists, using indexing)
print(f"First element: {my_tuple[0]}")
print(f"Last element: {my_tuple[-1]}")

# Slicing tuples (also similar to lists)
print(f"Slice from index 1 to 3 (exclusive): {my_tuple[1:3]}")

"""### Tuple Methods

Tuples have fewer methods than lists because of their immutability. The most common methods are `count()` and `index()`.
"""

my_tuple_with_duplicates = (1, 2, 2, 3, 4, 2)

# count(): Returns the number of times a specified value occurs in a tuple
print(f"Number of '2's in my_tuple_with_duplicates: {my_tuple_with_duplicates.count(2)}")

# index(): Searches the tuple for a specified value and returns the position of where it was found
# If the value is not found, it raises a ValueError
print(f"Index of '3' in my_tuple_with_duplicates: {my_tuple_with_duplicates.index(3)}")

# You can also use 'in' operator to check for membership
print(f"Is '4' in my_tuple_with_duplicates? {'4' in my_tuple_with_duplicates}")

"""### Immutability in Action

Because tuples are immutable, you cannot change their elements after creation. Attempting to do so will result in a `TypeError`.
"""

another_tuple = ('apple', 'banana', 'cherry')

# Uncommenting the line below would cause a TypeError:
# another_tuple[0] = 'orange'
# print(another_tuple)

print("Attempting to modify a tuple element directly will result in a TypeError.")
print("For example: another_tuple[0] = 'orange' will fail.")

# You also cannot add or remove elements after creation
# another_tuple.append('grape') # This would also cause an AttributeError (tuples don't have an 'append' method)
# another_tuple.remove('banana') # This would also cause an AttributeError

converted_list = list(tuple_1)
print(f"Original tuple: {tuple_1}")
print(f"Converted list: {converted_list}")
print(f"Type of converted_list: {type(converted_list)}")

"""## Understanding Sets

Sets are unordered collections of **unique** items. This means that a set cannot have duplicate elements. They are mutable, which implies that you can add or remove items from a set after it's created. Sets are commonly used for tasks involving uniqueness, membership testing, and mathematical set operations like union, intersection, difference, and symmetric difference.

**Key characteristics of sets:**
*   **Unordered**: Items in a set do not have a defined order, and you cannot access them using indexes.
*   **Unique Elements**: Each element in a set must be unique; duplicates are automatically removed.
*   **Mutable**: You can add or remove elements after creation.
*   **No Indexing/Slicing**: Due to their unordered nature, sets do not support indexing or slicing.
*   **Iterable**: You can iterate over the elements of a set.
*   **Hashable Elements**: Only immutable (hashable) objects can be stored within a set. Therefore, lists or other sets cannot be elements of a set.
"""

# Creating a set
my_set = {'apple', 'banana', 'cherry', 'apple', 'date'}
print(f"My set: {my_set}")
print(f"Type of my_set: {type(my_set)}")

# Notice how 'apple' only appears once, as sets store only unique elements.

"""### Checking for Item Existence in a Set

To check if an item exists within a set, you can use the `in` operator, similar to how you would for lists or tuples. This operation is highly efficient for sets due to their underlying hash-based implementation.
"""

# Check if 'banana' is in the set
is_banana_present = 'banana' in my_set
print(f"Is 'banana' in my_set? {is_banana_present}")

# Check if 'grape' is in the set
is_grape_present = 'grape' in my_set
print(f"Is 'grape' in my_set? {is_grape_present}")

# Check if 'apple' is in the set
is_apple_present = 'apple' in my_set
print(f"Is 'apple' in my_set? {is_apple_present}")

cs_courses = {'Maths','Sci','English','Hindi','Physics'}
art_courses = {'Maths','English','Tamil','Art'}

print(cs_courses.intersection(art_courses))

#empty list
empty_list = []
empty_list = list()

#empty tuple
empty_tuple = ()
empty_tuple = tuple()

#empty set
empty_set = {} # This isn't right! It's a dict
empty_set = set()

