# -*- coding: utf-8 -*-
"""Numpy_Basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVkJ6jgd57db4j7Zuvf_PjorLHGGr7RT
"""

import numpy as np

array = np.array([4,5,8,2,9])

array = array * 2
print(array)
print(type(array))



"""multidimensional array"""

array = np.array([[['a','b','c'], ['d','e','f'],['g','h','i']],
                  [['j','k','l'], ['m','n','o'],['p','q','r']],
                  [['s','t','u'], ['v','w','x'],['y','z',' ']]])

print(array.ndim)

array = np.array([[['a','b','c'], ['d','e','f'],['g','h','i']],
                  [['j','k','l'], ['m','n','o'],['p','q','r']],
                  [['s','t','u'], ['v','w','x'],['y','z',' ']]])

print(array.shape)

"""Slicing"""

array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12,],
                 [13,14,15,16]])

# array[start:end:step]

print(array[0:4:2])
print(array[2:4])

print(array[::-1])

array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12,],
                 [13,14,15,16]])

# array[start:end:step]


print(array[:,::-1])

print(array[0:2,0:3])

"""#Scalar arithemetic"""

array = np.array([2,4,6])

print(array + 4)

print(array * 2)

print(array - 4)

print(array / 4)

print(array ** 4)

"""# Vectorized math funcs"""

array = np.array([1,2,3,2.5])
print(np.sqrt(array))
print(np.exp(array))
print(np.log(array))
print(np.sin(array))
print(np.round(array))

"""exercise"""

radii = np.array([1,2,3,4,5])

print( np.pi * radii ** 2)

"""# Element-wise-arithmetic"""

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

"""# comparison operatoors"""

scores = np.array([20,30,40,55,66,77])

print(scores > 50)
print(scores < 50)
print(scores >= 50)
print(scores <= 50)
print(scores == 50)
print(scores != 50)

scores[scores < 60 ] = 0
print(scores)

